### ISSUE TITLE
Add a Converter to Transform Source Text into Incorrect Words

### ISSUE THREAD

**Issue by amused201** [ArpanDhot/Grammer-AI-corrector#1]
**Description:**

It would be useful to implement a feature that converts correctly written source text into intentionally incorrect words. This could serve as a testing mechanism for the Grammar-AI Corrector model, enabling developers to evaluate its performance under controlled error conditions.

### Proposed Implementation:
1. **Input:** Accept a string of correctly written text.
2. **Processing:**
   - Introduce grammatical, spelling, and syntactical errors programmatically.
   - Randomize error placement to mimic natural human errors.
3. **Output:** Return the transformed text with intentional errors.

### Use Cases:
- Testing and benchmarking the Grammar-AI Corrector.
- Generating datasets for training or testing purposes.

### Key Considerations:
- Ensure diversity in error types (e.g., verb conjugation mistakes, spelling errors, missing punctuation).
- Allow customization for the level and type of errors introduced.
- Option to integrate this feature as a standalone tool or as part of the existing workflow.

### Example:
**Input:** "The cat is on the mat."
**Output:** "Teh cat are in teh mat"

This feature will enhance the utility of the repository and contribute to robust AI model evaluation.

**Comment by ArpanDhot** [comment]
@amused201 Thank you for your interest in the project! This feature is already available. If you need further assistance, feel free to reach out. I will close this issue for now, but please don’t hesitate to create a new issue if any problems arise.
